/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Usuario;
import Classes.Personagem;
import DB.PersonagemDAO;
import DB.UsuarioDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author guest-jxkfif
 */
public class TelaInicialPersonagem extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicialPersonagem
     * 
     */
    Usuario user;
    PersonagemDAO personDAO;
    UsuarioDAO userDAO;
    ArrayList<Personagem> todosOsPersonagens = new ArrayList();
    ArrayList<Personagem> personagensSelecionados = new ArrayList();
    
    public TelaInicialPersonagem() {
        initComponents();
    }
    
    private void preencherCamposPersonagens(ArrayList<Personagem> personagens)
    {
        for(int i = -1; i < personagens.size(); i++) {
            switch (i) {
                case 0 -> CTpersonagem1.setText(personagens.get(i).getNome());
                case 1 -> CTpersonagem2.setText(personagens.get(i).getNome());
                case 2 -> CTpersonagem3.setText(personagens.get(i).getNome());
                case 3 -> CTpersonagem4.setText(personagens.get(i).getNome());
                case 4 -> CTpersonagem5.setText(personagens.get(i).getNome());
                default -> {
                }
            }
        }
    }
    
    public void limparCamposPersonagens()
    {
        CTpersonagem1.setText("");
        CTpersonagem2.setText("");
        CTpersonagem3.setText("");
        CTpersonagem4.setText("");
        CTpersonagem5.setText("");
    }
    
    public void removerPersonagemComCampo(int campo)
    {
        if(personagensSelecionados.size() >= campo)
        {
            personDAO.removerPersonagem(personagensSelecionados.get(campo - 1));
            todosOsPersonagens = userDAO.pesquisarPersonagens(user);
            personagensSelecionados.clear();
            personagensSelecionados.addAll(todosOsPersonagens);
            limparCamposPersonagens();
            preencherCamposPersonagens(todosOsPersonagens);
            RadioBtnTodas.setSelected(true);
        }
    }
    
    public TelaInicialPersonagem(Usuario us) {
        initComponents();
        user = us;
        userDAO = new UsuarioDAO();
        personDAO = new PersonagemDAO();
        todosOsPersonagens = userDAO.pesquisarPersonagens(user);
        personagensSelecionados.addAll(todosOsPersonagens);
        preencherCamposPersonagens(todosOsPersonagens);
        
        LBnome.setText(user.getNome());
        RadioBtnTodas.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        BTsair = new javax.swing.JButton();
        LBnome = new javax.swing.JLabel();
        LBbemvindo = new javax.swing.JLabel();
        BtnCriarPersonagem = new javax.swing.JButton();
        BtnApagarConta = new javax.swing.JButton();
        BtnEditar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        CTpersonagem2 = new javax.swing.JTextField();
        CTpersonagem3 = new javax.swing.JTextField();
        CTpersonagem4 = new javax.swing.JTextField();
        CTpersonagem1 = new javax.swing.JTextField();
        CTpersonagem5 = new javax.swing.JTextField();
        BtnDeletar1 = new javax.swing.JButton();
        BtnEditar2 = new javax.swing.JButton();
        BtnDeletar2 = new javax.swing.JButton();
        BtnEditar3 = new javax.swing.JButton();
        BtnDeletar3 = new javax.swing.JButton();
        BtnEditar4 = new javax.swing.JButton();
        BtnDeletar4 = new javax.swing.JButton();
        BtnEditar5 = new javax.swing.JButton();
        BtnDeletar5 = new javax.swing.JButton();
        BtnAlterarCadastro = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        RadioBtnGuerreiro = new javax.swing.JRadioButton();
        RadioBtnTodas = new javax.swing.JRadioButton();
        RadioBtnBandido = new javax.swing.JRadioButton();
        RadioBtnClerigo = new javax.swing.JRadioButton();
        RadioBtnMago = new javax.swing.JRadioButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        BTsair.setText("Sair");
        BTsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTsairActionPerformed(evt);
            }
        });

        LBnome.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LBnome.setText("NOME#0000");

        LBbemvindo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        LBbemvindo.setText("Bem-vindo, ");

        BtnCriarPersonagem.setText("Criar Novo Personagem");
        BtnCriarPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCriarPersonagemActionPerformed(evt);
            }
        });

        BtnApagarConta.setText("<html>Apagar<br/>conta</html>");
        BtnApagarConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnApagarContaActionPerformed(evt);
            }
        });

        BtnEditar1.setText("Editar");
        BtnEditar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditar1ActionPerformed(evt);
            }
        });

        CTpersonagem2.setEditable(false);
        CTpersonagem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CTpersonagem2MouseClicked(evt);
            }
        });

        CTpersonagem3.setEditable(false);
        CTpersonagem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CTpersonagem3MouseClicked(evt);
            }
        });
        CTpersonagem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTpersonagem3ActionPerformed(evt);
            }
        });

        CTpersonagem4.setEditable(false);
        CTpersonagem4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CTpersonagem4MouseClicked(evt);
            }
        });

        CTpersonagem1.setEditable(false);
        CTpersonagem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CTpersonagem1MouseClicked(evt);
            }
        });

        CTpersonagem5.setEditable(false);
        CTpersonagem5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CTpersonagem5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CTpersonagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CTpersonagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CTpersonagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CTpersonagem4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CTpersonagem5, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CTpersonagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CTpersonagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CTpersonagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CTpersonagem4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CTpersonagem5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        BtnDeletar1.setText("Deletar");
        BtnDeletar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeletar1ActionPerformed(evt);
            }
        });

        BtnEditar2.setText("Editar");
        BtnEditar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditar2ActionPerformed(evt);
            }
        });

        BtnDeletar2.setText("Deletar");
        BtnDeletar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeletar2ActionPerformed(evt);
            }
        });

        BtnEditar3.setText("Editar");
        BtnEditar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditar3ActionPerformed(evt);
            }
        });

        BtnDeletar3.setText("Deletar");
        BtnDeletar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeletar3ActionPerformed(evt);
            }
        });

        BtnEditar4.setText("Editar");
        BtnEditar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditar4ActionPerformed(evt);
            }
        });

        BtnDeletar4.setText("Deletar");
        BtnDeletar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeletar4ActionPerformed(evt);
            }
        });

        BtnEditar5.setText("Editar");
        BtnEditar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditar5ActionPerformed(evt);
            }
        });

        BtnDeletar5.setText("Deletar");
        BtnDeletar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeletar5ActionPerformed(evt);
            }
        });

        BtnAlterarCadastro.setText("Alterar dados Cadastrais");
        BtnAlterarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAlterarCadastroActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioBtnGuerreiro);
        RadioBtnGuerreiro.setText("Guerreiro");
        RadioBtnGuerreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtnGuerreiroActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioBtnTodas);
        RadioBtnTodas.setText("Todas");
        RadioBtnTodas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtnTodasActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioBtnBandido);
        RadioBtnBandido.setText("Bandido");
        RadioBtnBandido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtnBandidoActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioBtnClerigo);
        RadioBtnClerigo.setText("Clerigo");
        RadioBtnClerigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtnClerigoActionPerformed(evt);
            }
        });

        buttonGroup1.add(RadioBtnMago);
        RadioBtnMago.setText("Mago");
        RadioBtnMago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtnMagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(RadioBtnTodas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioBtnGuerreiro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioBtnBandido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RadioBtnClerigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RadioBtnMago, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioBtnGuerreiro)
                            .addComponent(RadioBtnClerigo))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioBtnBandido)
                            .addComponent(RadioBtnMago)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(RadioBtnTodas)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BTsair)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnApagarConta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtnAlterarCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(BtnCriarPersonagem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnEditar1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnDeletar1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnEditar2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnDeletar2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnEditar3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnDeletar3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnEditar4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnDeletar4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BtnEditar5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(BtnDeletar5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(LBbemvindo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LBnome)))))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LBbemvindo)
                    .addComponent(LBnome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnEditar1)
                            .addComponent(BtnDeletar1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnEditar2)
                            .addComponent(BtnDeletar2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnEditar3)
                            .addComponent(BtnDeletar3))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnEditar4)
                            .addComponent(BtnDeletar4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnEditar5)
                            .addComponent(BtnDeletar5))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCriarPersonagem)
                    .addComponent(BtnAlterarCadastro))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnApagarConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTsair))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CTpersonagem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CTpersonagem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CTpersonagem3ActionPerformed

    private void BtnCriarPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCriarPersonagemActionPerformed
        if(todosOsPersonagens.size() < 5)
        {
            TelaDefinirClasse telaDefClasse = new TelaDefinirClasse(user);
            telaDefClasse.setVisible(true);
            dispose();
        }else
        {
            JOptionPane.showMessageDialog(null, "Limite de 5 personagens atingido!");
        }
    }//GEN-LAST:event_BtnCriarPersonagemActionPerformed

    private void BTsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTsairActionPerformed
        TelaLoginCadastroUsuario telalogUser = new TelaLoginCadastroUsuario();
        telalogUser.setVisible(true);
        dispose();
    }//GEN-LAST:event_BTsairActionPerformed

    private void BtnApagarContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnApagarContaActionPerformed
        TelaConfirmarApagarConta telaApagar = new TelaConfirmarApagarConta(user, this);
        telaApagar.setVisible(true);
    }//GEN-LAST:event_BtnApagarContaActionPerformed

    private void BtnEditar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditar1ActionPerformed
        if(!personagensSelecionados.isEmpty())
        {
            TelaEditarPersonagem telaEditar = new TelaEditarPersonagem(user, personagensSelecionados.get(0));
            telaEditar.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_BtnEditar1ActionPerformed

    private void BtnDeletar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeletar1ActionPerformed
        if(!BtnDeletar1.getText().isEmpty())
        {
            removerPersonagemComCampo(1);
            
        }
    }//GEN-LAST:event_BtnDeletar1ActionPerformed

    private void BtnDeletar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeletar2ActionPerformed
        if(!BtnDeletar2.getText().isEmpty())
        {
            removerPersonagemComCampo(2);
        }
    }//GEN-LAST:event_BtnDeletar2ActionPerformed

    private void BtnDeletar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeletar3ActionPerformed
        if(!BtnDeletar3.getText().isEmpty())
        {
            removerPersonagemComCampo(3);
        }
    }//GEN-LAST:event_BtnDeletar3ActionPerformed

    private void BtnDeletar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeletar4ActionPerformed
        if(!BtnDeletar4.getText().isEmpty())
        {
            removerPersonagemComCampo(4);
        }
    }//GEN-LAST:event_BtnDeletar4ActionPerformed

    private void BtnDeletar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeletar5ActionPerformed
        if(!BtnDeletar5.getText().isEmpty())
        {
            removerPersonagemComCampo(5);
        }
    }//GEN-LAST:event_BtnDeletar5ActionPerformed

    private void BtnEditar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditar2ActionPerformed
        if(personagensSelecionados.size() > 1)
        {
            TelaEditarPersonagem telaEditar = new TelaEditarPersonagem(user, personagensSelecionados.get(1));
            telaEditar.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_BtnEditar2ActionPerformed

    private void BtnEditar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditar3ActionPerformed
        if(personagensSelecionados.size() > 2)
        {
            TelaEditarPersonagem telaEditar = new TelaEditarPersonagem(user, personagensSelecionados.get(2));
            telaEditar.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_BtnEditar3ActionPerformed

    private void BtnEditar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditar4ActionPerformed
        if(personagensSelecionados.size() > 3)
        {
            TelaEditarPersonagem telaEditar = new TelaEditarPersonagem(user, personagensSelecionados.get(3));
            telaEditar.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_BtnEditar4ActionPerformed

    private void BtnEditar5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditar5ActionPerformed
        if(personagensSelecionados.size() > 4)
        {
            TelaEditarPersonagem telaEditar = new TelaEditarPersonagem(user, personagensSelecionados.get(4));
            telaEditar.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_BtnEditar5ActionPerformed

    private void BtnAlterarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAlterarCadastroActionPerformed
        TelaAlterarCadastro telaAlterar = new TelaAlterarCadastro(user, this);
        telaAlterar.setVisible(true);
    }//GEN-LAST:event_BtnAlterarCadastroActionPerformed

    private void RadioBtnBandidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtnBandidoActionPerformed
        limparCamposPersonagens();
        personagensSelecionados.clear();
        
        for(int i = 0; i < todosOsPersonagens.size(); i++)
        {
            if(todosOsPersonagens.get(i).getClasse().equals("Bandido"))
            {
                personagensSelecionados.add(todosOsPersonagens.get(i));
            }
        }
        preencherCamposPersonagens(personagensSelecionados);
    }//GEN-LAST:event_RadioBtnBandidoActionPerformed

    private void RadioBtnTodasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtnTodasActionPerformed
        limparCamposPersonagens();
        personagensSelecionados.clear();
        personagensSelecionados.addAll(todosOsPersonagens);
        preencherCamposPersonagens(personagensSelecionados);
    }//GEN-LAST:event_RadioBtnTodasActionPerformed

    private void RadioBtnGuerreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtnGuerreiroActionPerformed
        limparCamposPersonagens();
        personagensSelecionados.clear();
        
        for(int i = 0; i < todosOsPersonagens.size(); i++)
        {
            if(todosOsPersonagens.get(i).getClasse().equals("Guerreiro"))
            {
                personagensSelecionados.add(todosOsPersonagens.get(i));
            }
        }
        preencherCamposPersonagens(personagensSelecionados);
    }//GEN-LAST:event_RadioBtnGuerreiroActionPerformed

    private void RadioBtnClerigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtnClerigoActionPerformed
        limparCamposPersonagens();
        personagensSelecionados.clear();
        
        for(int i = 0; i < todosOsPersonagens.size(); i++)
        {
            if(todosOsPersonagens.get(i).getClasse().equals("Clerigo"))
            {
                personagensSelecionados.add(todosOsPersonagens.get(i));
            }
        }
        preencherCamposPersonagens(personagensSelecionados);
    }//GEN-LAST:event_RadioBtnClerigoActionPerformed

    private void RadioBtnMagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtnMagoActionPerformed
        limparCamposPersonagens();
        personagensSelecionados.clear();
        
        for(int i = 0; i < todosOsPersonagens.size(); i++)
        {
            if(todosOsPersonagens.get(i).getClasse().equals("Mago"))
            {
                personagensSelecionados.add(todosOsPersonagens.get(i));
            }
        }
        preencherCamposPersonagens(personagensSelecionados);
    }//GEN-LAST:event_RadioBtnMagoActionPerformed

    private void CTpersonagem1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CTpersonagem1MouseClicked
        if(!personagensSelecionados.isEmpty())
        {
            TelaDetalhesPersonagem telaDetalhes = new TelaDetalhesPersonagem(personagensSelecionados.get(0));
            telaDetalhes.setVisible(true);
        }

    }//GEN-LAST:event_CTpersonagem1MouseClicked

    private void CTpersonagem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CTpersonagem2MouseClicked
        if(personagensSelecionados.size() > 1)
        {
            TelaDetalhesPersonagem telaDetalhes = new TelaDetalhesPersonagem(personagensSelecionados.get(1));
            telaDetalhes.setVisible(true);
        }
    }//GEN-LAST:event_CTpersonagem2MouseClicked

    private void CTpersonagem3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CTpersonagem3MouseClicked
        if(personagensSelecionados.size() > 2)
        {
            TelaDetalhesPersonagem telaDetalhes = new TelaDetalhesPersonagem(personagensSelecionados.get(2));
            telaDetalhes.setVisible(true);
        }
    }//GEN-LAST:event_CTpersonagem3MouseClicked

    private void CTpersonagem4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CTpersonagem4MouseClicked
        if(personagensSelecionados.size() > 3)
        {
            TelaDetalhesPersonagem telaDetalhes = new TelaDetalhesPersonagem(personagensSelecionados.get(3));
            telaDetalhes.setVisible(true);
        }
    }//GEN-LAST:event_CTpersonagem4MouseClicked

    private void CTpersonagem5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CTpersonagem5MouseClicked
        if(personagensSelecionados.size() > 4)
        {
            TelaDetalhesPersonagem telaDetalhes = new TelaDetalhesPersonagem(personagensSelecionados.get(4));
            telaDetalhes.setVisible(true);
        }
    }//GEN-LAST:event_CTpersonagem5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialPersonagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialPersonagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTsair;
    private javax.swing.JButton BtnAlterarCadastro;
    private javax.swing.JButton BtnApagarConta;
    private javax.swing.JButton BtnCriarPersonagem;
    private javax.swing.JButton BtnDeletar1;
    private javax.swing.JButton BtnDeletar2;
    private javax.swing.JButton BtnDeletar3;
    private javax.swing.JButton BtnDeletar4;
    private javax.swing.JButton BtnDeletar5;
    private javax.swing.JButton BtnEditar1;
    private javax.swing.JButton BtnEditar2;
    private javax.swing.JButton BtnEditar3;
    private javax.swing.JButton BtnEditar4;
    private javax.swing.JButton BtnEditar5;
    private javax.swing.JTextField CTpersonagem1;
    private javax.swing.JTextField CTpersonagem2;
    private javax.swing.JTextField CTpersonagem3;
    private javax.swing.JTextField CTpersonagem4;
    private javax.swing.JTextField CTpersonagem5;
    private javax.swing.JLabel LBbemvindo;
    private javax.swing.JLabel LBnome;
    private javax.swing.JRadioButton RadioBtnBandido;
    private javax.swing.JRadioButton RadioBtnClerigo;
    private javax.swing.JRadioButton RadioBtnGuerreiro;
    private javax.swing.JRadioButton RadioBtnMago;
    private javax.swing.JRadioButton RadioBtnTodas;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
