/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author guest-pnhekr
 */
public class TelaDefinirClasse extends javax.swing.JFrame {

    /**
     * Creates new form DefinirClasse
     */
    Usuario user;
    
    public TelaDefinirClasse(Usuario us) {
        initComponents();
        user = us;
    }
    
    public TelaDefinirClasse() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnGroupClasses = new javax.swing.ButtonGroup();
        BtnGroupGenero = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        BtnVoltar = new javax.swing.JButton();
        RadioBtnBandido = new javax.swing.JRadioButton();
        RadioBtnClerigo = new javax.swing.JRadioButton();
        RadioBtnGuerreiro = new javax.swing.JRadioButton();
        RadioBtnMago = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAhabilidades = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        RadioBtnMasculino = new javax.swing.JRadioButton();
        RadioBtnFeminino = new javax.swing.JRadioButton();
        BtnProximo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Selecione a classe!");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Selecione a classe:");
        jLabel1.setMaximumSize(new java.awt.Dimension(140, 40));
        jLabel1.setMinimumSize(new java.awt.Dimension(140, 40));
        jLabel1.setPreferredSize(new java.awt.Dimension(136, 15));

        BtnVoltar.setText("Voltar");
        BtnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVoltarActionPerformed(evt);
            }
        });

        BtnGroupClasses.add(RadioBtnBandido);
        RadioBtnBandido.setText("Bandido");
        RadioBtnBandido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtnBandidoActionPerformed(evt);
            }
        });

        BtnGroupClasses.add(RadioBtnClerigo);
        RadioBtnClerigo.setText("Clérigo");
        RadioBtnClerigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtnClerigoActionPerformed(evt);
            }
        });

        BtnGroupClasses.add(RadioBtnGuerreiro);
        RadioBtnGuerreiro.setText("Guerreiro");
        RadioBtnGuerreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtnGuerreiroActionPerformed(evt);
            }
        });

        BtnGroupClasses.add(RadioBtnMago);
        RadioBtnMago.setText("Mago");
        RadioBtnMago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtnMagoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Habilidades:");

        TAhabilidades.setEditable(false);
        TAhabilidades.setColumns(20);
        TAhabilidades.setRows(5);
        jScrollPane1.setViewportView(TAhabilidades);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Selecione o gênero:");

        BtnGroupGenero.add(RadioBtnMasculino);
        RadioBtnMasculino.setText("Masculino");

        BtnGroupGenero.add(RadioBtnFeminino);
        RadioBtnFeminino.setText("Feminino");

        BtnProximo.setText("Próximo");
        BtnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(BtnVoltar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RadioBtnMago, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RadioBtnBandido)
                                    .addComponent(RadioBtnClerigo)
                                    .addComponent(RadioBtnGuerreiro)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RadioBtnFeminino, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RadioBtnMasculino, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RadioBtnBandido)
                        .addGap(10, 10, 10)
                        .addComponent(RadioBtnClerigo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RadioBtnGuerreiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RadioBtnMago))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RadioBtnMasculino)
                    .addComponent(BtnProximo))
                .addGap(8, 8, 8)
                .addComponent(RadioBtnFeminino)
                .addGap(22, 22, 22)
                .addComponent(BtnVoltar)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RadioBtnMagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtnMagoActionPerformed
        TAhabilidades.setText("1 Arma Branca Leve\n1 Cajado\n+5 de Inteligência");
    }//GEN-LAST:event_RadioBtnMagoActionPerformed

    private void BtnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVoltarActionPerformed
        TelaInicialPersonagem telaInicial = new TelaInicialPersonagem(user);
        telaInicial.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnVoltarActionPerformed

    private void RadioBtnBandidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtnBandidoActionPerformed
        TAhabilidades.setText("2 Armas Brancas Leves\n+5 de Destreza");
    }//GEN-LAST:event_RadioBtnBandidoActionPerformed

    private void RadioBtnClerigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtnClerigoActionPerformed
        TAhabilidades.setText("1 Arma Branca Pesada\n1 Talisman\n+5 de Fé");
    }//GEN-LAST:event_RadioBtnClerigoActionPerformed

    private void RadioBtnGuerreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtnGuerreiroActionPerformed
        TAhabilidades.setText("2 Armas Brancas Pesadas\n+5 de Força");
    }//GEN-LAST:event_RadioBtnGuerreiroActionPerformed

    private void BtnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnProximoActionPerformed
        String classe = new String();
        String gender = "";
        boolean classeSelecionada = true;
        boolean GeneroSelecionado = true;
        
        if(RadioBtnGuerreiro.isSelected()) {
            classe = "Guerreiro";
        }else if(RadioBtnBandido.isSelected()) {
            classe = "Bandido";
        }else if(RadioBtnClerigo.isSelected()) {
            classe = "Clerigo";
        }else if(RadioBtnMago.isSelected()) {
            classe = "Mago";
        }else
        {
            JOptionPane.showMessageDialog(null, "Classe é obrigatória!");
            classeSelecionada = false;
        }
        
        if(classeSelecionada)
        {
            if(RadioBtnMasculino.isSelected()) {
                gender = "M";
            }else if(RadioBtnFeminino.isSelected()) {
                gender = "F";
            }else
            {
                JOptionPane.showMessageDialog(null, "Gênero é obrigatório!");
                GeneroSelecionado = false;
            }
            
            if(GeneroSelecionado)
            {
                TelaCriacaoPersonagem telaCriacao = new TelaCriacaoPersonagem(user, gender, classe);
                telaCriacao.setVisible(true);
                dispose();
            }

        }

    }//GEN-LAST:event_BtnProximoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDefinirClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDefinirClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDefinirClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDefinirClasse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDefinirClasse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BtnGroupClasses;
    private javax.swing.ButtonGroup BtnGroupGenero;
    private javax.swing.JButton BtnProximo;
    private javax.swing.JButton BtnVoltar;
    private javax.swing.JRadioButton RadioBtnBandido;
    private javax.swing.JRadioButton RadioBtnClerigo;
    private javax.swing.JRadioButton RadioBtnFeminino;
    private javax.swing.JRadioButton RadioBtnGuerreiro;
    private javax.swing.JRadioButton RadioBtnMago;
    private javax.swing.JRadioButton RadioBtnMasculino;
    private javax.swing.JTextArea TAhabilidades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
